### ISSUE TITLE
About src/nao/dependencies.repos

### ISSUE THREAD

**Issue by kyky233** [ijnek/nao#3]
![image](https://github.com/ijnek/nao/assets/46394768/b8079bfa-138f-459c-ae2c-4a5b9d4327b9)

Hello, I found you mentioned _src/nao/dependencies.repos_ in your steps to clone repositories, but there is not any file called _dependencies.repos_ in your repo. 
I am not sure if you have missed that file, if so, could you please upload it again? 
Many thanks.

**Comment by ijnek** [comment]
The dependencies.repos is not required anymore as the dependencies are available as binaries. I have [updated the documentation](https://github.com/ijnek/nao-docs/blob/main/installation.rst) to ensure the binary dependency is installed using ``rosdep``. Thank you for your the heads up!
